### ISSUE TITLE
add support for syntax highlighting for `Copy` and `Paste` commands

### ISSUE THREAD

**Issue by Delta456** [charmbracelet/tree-sitter-vhs#12]
**Is your feature request related to a problem? Please describe.**
The current `tree-sitter` doesn't have support for `Copy` and `Paste`

**Describe the solution you'd like**
Add support for these commands

**Describe alternatives you've considered**
This feature can be added simply and doesn't need any alternative.

**Additional context**
I will work on adding support for this.

**Comment by maaslalani** [comment]
This is now added! Thanks so much for the issue!
