### ISSUE TITLE
tree-sitter-go 

### ISSUE THREAD

**Issue by gedw99** [charmbracelet/tree-sitter-vhs#5]
https://github.com/tree-sitter/tree-sitter-go

make its easy to build your own gui with syntax highlighting.

for example with gum or gio perhaps

**Comment by gedw99** [comment]
my mistake its a grammar for golang the language, not a runner time in golang for tree sitter !!  - dooh

**Comment by maaslalani** [comment]
No problem! Thank you for the issue ❤️
