### ISSUE TITLE
Regular expression for `time` matches incorrectly

### ISSUE THREAD

**Issue by uncenter** [charmbracelet/tree-sitter-vhs#9]
https://github.com/charmbracelet/tree-sitter-vhs/blob/fec6e981b7795b68262ddf229d73d2aa03a89b9a/grammar.js#L75C34-L75C34
```js
time: $ =>    /\d*\.?\d+m?s?/,
```

The regex `/\d*\.?\d+m?s?/` correctly matches integers and floats followed by `ms` and `s` but also those followed by just `m` since the `s` is optional (`s?`). Is this intentional? `Sleep 5m` is an invalid tape command so it probably shouldn't be highlighted until the full `ms` is typed.

**Comment by maaslalani** [comment]
Ah, you're absolutely correct, it should only highlight `ms` and `s` since `m` is not supported.

**Comment by maaslalani** [comment]
Fixed in: https://github.com/charmbracelet/tree-sitter-vhs/commit/9534865e614c95eb9418e5e73f061c32fa4d9540

**Comment by uncenter** [comment]
Awesome! Thank you for taking a look.
